# generated by appcreator
import django_filters
from django import forms
from . models import AboutTheProject, TeamMember


class TeamMemberListFilter(django_filters.FilterSet):

    class Meta:
        model = TeamMember
        fields = "__all__"


class AboutTheProjectListFilter(django_filters.FilterSet):

    class Meta:
        model = AboutTheProject
        fields = "__all__"
