# generated by appcreator
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from . filters import *
from . forms import *
from . tables import AboutTheProjectTable
from . models import AboutTheProject
from browsing.browsing_utils import GenericListView, BaseCreateView, BaseUpdateView


class AboutTheProjectListView(GenericListView):

    model = AboutTheProject
    filter_class = AboutTheProjectListFilter
    formhelper_class = AboutTheProjectFilterFormHelper
    table_class = AboutTheProjectTable
    init_columns = [
        'id', 'description',
    ]


class AboutTheProjectDetailView(DetailView):

    model = AboutTheProject
    template_name = 'browsing/generic_detail.html'


class AboutTheProjectCreate(BaseCreateView):

    model = AboutTheProject
    form_class = AboutTheProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AboutTheProjectCreate, self).dispatch(*args, **kwargs)


class AboutTheProjectUpdate(BaseUpdateView):

    model = AboutTheProject
    form_class = AboutTheProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AboutTheProjectUpdate, self).dispatch(*args, **kwargs)


class AboutTheProjectDelete(DeleteView):
    model = AboutTheProject
    template_name = 'webpage/confirm_delete.html'
    success_url = reverse_lazy('info:about_browse')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AboutTheProjectDelete, self).dispatch(*args, **kwargs)
