# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idprovider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.IdProvider')),
                ('name', models.CharField(blank=True, help_text='Alternative Name', max_length=250)),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.IdProvider')),
                ('legacy_id', models.CharField(blank=True, max_length=300)),
                ('written_name', models.CharField(blank=True, max_length=300)),
                ('authority_url', models.CharField(blank=True, max_length=300)),
                ('alt_names', models.CharField(blank=True, max_length=300)),
                ('abbreviation', models.CharField(blank=True, max_length=300)),
                ('comment', models.TextField(blank=True)),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.IdProvider')),
                ('legacy_id', models.CharField(blank=True, max_length=300)),
                ('written_name', models.CharField(blank=True, max_length=300)),
                ('forename', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('acad_title', models.CharField(blank=True, max_length=300)),
                ('alt_names', models.CharField(blank=True, max_length=300)),
                ('authority_url', models.CharField(blank=True, max_length=300)),
                ('comment', models.TextField(blank=True)),
                ('belongs_to_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_member', to='entities.Institution')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='idprovider.IdProvider')),
                ('name', models.CharField(blank=True, help_text='Normalized name', max_length=250)),
                ('geonames_id', models.CharField(blank=True, help_text='GND-ID', max_length=50)),
                ('lat', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True)),
                ('place_type', models.CharField(blank=True, choices=[('city', 'city'), ('country', 'country')], max_length=50, null=True)),
                ('alternative_name', models.ManyToManyField(blank=True, help_text='Alternative names', max_length=250, to='entities.AlternativeName')),
                ('part_of', models.ForeignKey(blank=True, help_text='A place (country) this place is part of.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_child', to='entities.Place')),
            ],
            bases=('idprovider.idprovider',),
        ),
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Place'),
        ),
        migrations.AddField(
            model_name='institution',
            name='parent_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_institutions', to='entities.Institution'),
        ),
    ]
